resources:
  repositories:
    - repository: common
      type: github
      name: UiPath/AzurePipelinesTemplates
      ref: master
      endpoint: UiPath

    - repository: templates
      type: github
      name: UiPath/AzurePipelinesTemplates
      ref: refs/tags/uipath.package-signing.1.0.0
      endpoint: UiPath

trigger:
  branches:
    include:
      - develop
      - mains/*
      - release/*
  paths:
    include:
      - '*'
    exclude:
      - .github
      
pool:
  vmImage: 'windows-latest'
  
variables:
  - template: .vsts-variables.yml

stages:
- template: .ci/main.yml