trigger:
  batch: true
  branches:
    include:
    - develop
    - master/DocumentUnderstandingProcess/*
  paths:
    include:
    - DocumentUnderstandingProcess/*
    - .pipelines/*
    - azure-pipelines-DocumentUnderstandingProcess.yml

pr: none
  # branches:
  #   include:
  #   - develop
  #   - master/DocumentUnderstandingProcess/*    
  # paths:
  #   include:
  #   - DocumentUnderstandingProcess/*
  #   - .pipelines/*
  #   - azure-pipelines-DocumentUnderstandingProcess.yml

variables:
  - template: .pipelines/variables/common.yml
  - name: projectPath
    value: 'DocumentUnderstandingProcess'
  - name: projectNuspec
    value: 'UiPath.Template.DocumentUnderstandingProcess.nuspec'

jobs:
  - template: .pipelines/jobs/ci.yml
    parameters: 
      projectPath: ${{ variables.projectPath }}
      projectNuspec: ${{ variables.projectNuspec }}

