parameters:

stages:
- stage: Build
  dependsOn: []
  displayName: Build
  jobs:
  - job: Build
    timeoutInMinutes: 120
    steps:
    - task: NuGetToolInstaller@1
      displayName: "Install nuget"

    - task: NuGetAuthenticate@0
      displayName: "Authenticate feeds"

