parameters: 
  projectPath: ""
  name: ""
  orchestratorConnection: ""
  templatePrefix: RunRPATests

jobs:
  - job: "Run_RPA_Test_for_${{ parameters.name }}"
    pool:
        vmImage: 'windows-latest'

    steps:
      - script: |
            cd $(Build.SourcesDirectory)\DocumentUnderstandingProcess\Tests
            pip install -r requirements.txt
            pytest -m "smoke" --env "${{ parameters.name }}" -v -s  --junitxml=junit/test-results-${{ parameters.name }}.xml
        displayName: "pytest-${{ parameters.name }}"
 
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: '**/test-*.xml'
          testRunTitle: 'Publish test results for Python ${{ parameters.name }}'

      - script: python -m pip install --upgrade pyyaml
        displayName: 'Install pip Yaml tools'

      - task: PythonScript@0
        displayName: "Generate test variation"
        inputs:
          scriptSource: 'filePath'
          scriptPath: '$(Build.SourcesDirectory)\.pipelines\scripts\DocumentUnderstandingProcess\DUTestDataGenerator.py'
          workingDirectory: '$(Build.SourcesDirectory)\.pipelines\scripts\DocumentUnderstandingProcess\'

      - task: AzureCLI@2
        inputs:
          azureSubscription: 'du-qa-process-framework-rg'
          scriptType: 'ps'
          scriptLocation: 'inlineScript'
          inlineScript: 'az vm start --resource-group du-qa-process-framework-rg --name du-qa-process-framework-vm'
          useGlobalConfig: true

      - task: UiPathInstallPlatform@4
        inputs:
          cliVersion: 'WIN_23.6.8581.19168'

      - task: UiPathTest@4
        displayName: 'Run tests'
        inputs:
          testTarget: 'TestProject'
          orchestratorConnection: '${{ parameters.orchestratorConnection }}'
          testProjectPath: '${{ parameters.projectPath }}'
          folderName: 'DU Process'
          traceLevel: 'Verbose'
          attachRobotLogs: true
