parameters: 
  projectPath: ""
  name: ""
  orchestratorConnection: ""
  templatePrefix: RunRPATests

jobs:
  - job: "Run_RPA_Test_for_${{ parameters.name }}"
    pool:
        vmImage: 'windows-latest'

    steps:
          
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'specific'
          project: 'df7c0791-bbd1-4e4a-bda8-da579714e9e8'
          pipeline: '1882'
          buildVersionToDownload: 'specific'
          buildId: '2890569'
          downloadType: 'single'
          artifactName: 'uipcli'
          downloadPath: '$(Build.SourcesDirectory)'
          
      - task: ExtractFiles@1
        displayName: "Extract CLI"
        inputs:
          archiveFilePatterns: '$(Build.SourcesDirectory)\uipcli\cli.zip'
          destinationFolder: '$(Build.SourcesDirectory)\uipcli'
          cleanDestinationFolder: false
          overwriteExistingFiles: true

      - task: UiPathInstallPlatform@2
        displayName: 'Install platform to cache internal tool'

      # Override UIPCLI with one that supports running tests from a nupkg
      - powershell: |
          Get-ChildItem $env:UIPCLIDirectory -Directory -ErrorAction Ignore | ForEach-Object -Process {
            $destination = [System.IO.Path]::Combine($_.FullName, "x64")
            
            Write-Host $("Source " + $env:Source)
            Write-Host $("Destination " + $destination)
            
            Write-Host $("Delete old CLI" + $destination)
            Remove-Item $destination -Recurse -Force
            
            Write-Host $("List content " + $destination)
            Get-ChildItem -Path $destination -ErrorAction Ignore -Recurse
            
            Write-Host $("Copy "+ $env:Source +" to " + $destination)
            
            Get-ChildItem $env:Source | ForEach-Object {
                Copy-Item -Path $_.FullName -Destination $destination -Recurse -Force
            }
            
            Write-Host $("List content " + $destination)
            Get-ChildItem -Path $destination -ErrorAction Ignore -Recurse
          }
        displayName: "Override UiPath CLI version"
        env:
          Source: "$(Build.SourcesDirectory)\\uipcli"
      
      - script: python -m pip install --upgrade pyyaml
        displayName: 'Install pip Yaml tools'

      - task: PythonScript@0
        displayName: "Generate test variation"
        inputs:
          scriptSource: 'filePath'
          scriptPath: '$(Build.SourcesDirectory)\.pipelines\scripts\DocumentUnderstandingProcess\DUTestDataGenerator.py'
          workingDirectory: '$(Build.SourcesDirectory)\.pipelines\scripts\DocumentUnderstandingProcess\'
          
      - task: UiPathTest@2
        displayName: 'Run tests'
        inputs:
          testTarget: 'TestProject'
          orchestratorConnection: '${{ parameters.orchestratorConnection }}'
          testProjectPath: '${{ parameters.projectPath }}'
          folderName: 'DU Process'
          traceLevel: 'Verbose'
          attachRobotLogs: true
 