trigger:
  batch: true
  branches:
    include:
    - develop
    - master/REFramework_Testing*
  paths:
    include:
    - REFramework_Testing/*
    - .pipelines/*


pr: none
  # branches:
  #   include:
  #   - develop
  #   - master/REFramework_Testing*
  # paths:
  #   include:
  #   - REFramework_Testing/*
  #   - .pipelines/*


variables:
  - template: ../variables/common.yml
  - name: projectPath
    value: 'REFramework_Testing'
  - name: projectNuspec
    value: 'UiPath.Template.REFramework_Testing.nuspec'

jobs:
  - template: ../jobs/ci.yml
    parameters: 
      projectPath: ${{ variables.projectPath }}
      projectNuspec: ${{ variables.projectNuspec }}

