trigger:
  branches:
    include:
    - testpipeline

pr: none

variables:
  - template: ../variables/common.yml
  - name: projectPath
    value: 'DocumentUnderstandingProcess'
  - name: projectNuspec
    value: 'UiPath.Template.DocumentUnderstandingProcess.nuspec'

jobs:
  - job: Test
    steps:
    - script: echo Dummy text for pipeline configuration!

