trigger:
  batch: true
  branches:
    include:
      - develop
      - master/*
      - release/*
  paths:
    include:
    - /TestAutomationProcess/*
    - /.pipelines/*

pr: 
  paths:
    include:
     - /TestAutomationProcess/*
     - /.pipelines/*

variables:
  - template: ../variables/common.yml
  - name: projectPath
    value: 'TestAutomationProcess'
  - name: projectNuspec
    value: 'UiPath.Template.TestAutomationProcess.nuspec'
  - name: UIPCLIDirectory
    value: "$(Agent.ToolsDirectory)\\uipcli"

stages:

- stage: Build
  dependsOn: Test
  jobs:
    - template: ../jobs/ci.yml
      parameters: 
        projectPath: ${{ variables.projectPath }}
        projectNuspec: ${{ variables.projectNuspec }}
