trigger:
  branches:
    include:
    - testpipeline

pr: none

variables:
  - template: ../variables/common.yml
  - name: projectPath
    value: 'DocumentUnderstandingProcess'
  - name: projectNuspec
    value: 'UiPath.Template.DocumentUnderstandingProcess.nuspec'

pool:
  vmImage: 'windows-latest'

jobs:
  - job: Test
    steps:
    - pwsh: |
        ## get the changed files
        $files=$(git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion))
        $temp=$files -split ' '
        $count=$temp.Length
        echo "Total changed $count files"
      
        For ($i=0; $i -lt $temp.Length; $i++)
        {
          $name=$temp[$i]
          echo "this is $name file"
        }
      displayName: "Hello"
